# Generated by Django 5.2.12 on 2026-03-04 22:21

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0002_premimumservices'),
    ]

    operations = [
        migrations.CreateModel(
            name='Writer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('rate', models.CharField(max_length=100)),
                ('projects', models.CharField(max_length=150)),
                ('image', models.ImageField(upload_to='writers/')),
                ('description', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='WriterSkill',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('writer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='skills', to='assignment.writer')),
            ],
        ),
    ]
