# Generated by Django 5.2.12 on 2026-03-06 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('assignment', '0006_pageseo'),
    ]

    operations = [
        migrations.CreateModel(
            name='WorkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255)),
                ('discipline', models.CharField(max_length=200)),
                ('level', models.CharField(max_length=200)),
                ('pages', models.CharField(max_length=50)),
                ('format', models.CharField(max_length=100)),
                ('file', models.FileField(upload_to='samples/')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
    ]
